baseURL = 'https://edwor.my/'
languageCode = 'en-us'
title = '- edmund hattle -'
theme = ["hugo-embed-pdf-shortcode", "hugo-bearcub"]
enableInlineShortcodes = true
disableKinds = ["RSS"]
showdate = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    name = 'about'
    url = '/'
    weight = 6
  [[menu.main]]
    name = 'projects'
    url = '/projects/'
    weight = 7
  [[menu.main]]
    name = 'games'
    url = '/games/'
    weight = 60
  [[menu.main]]
    name = 'cv'
    url = '/cv/'
    weight = 70
  [[menu.main]]
    name = 'contact me'
    url = '/contact/'
    weight = 71
  [[menu.main]]
    name = 'art'
    url = '/art/'
    weight = 69
  
